---
dist: xenial
sudo: true
language: python
python:
  - 3.7
env:
  - ANSIBLE_LINT=4.1
  - ANSIBLE_LINT=3.5


before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats

install:
  - pip install ansible-lint==${ANSIBLE_LINT}

script:
  - bats ./tests/deprecated_vars.bats

notification:
  email: false
