---
dist: xenial
sudo: true
language: python

python:
  - 3.7
env:
  - ANSIBLE_LINT=4.1
  - ANSIBLE_LINT=3.5

install:
  - pip install ansible-lint==${ANSIBLE_LINT}

script:
  - ansible-lint -R -r lint/rules site.yml

notification:
  email: false
